### ISSUE TITLE
dotnet test fails in Linux build environments on resource folder path / file pt-BR not found - case sensitivity issue?

### ISSUE THREAD

**Issue by richardbartley** [MarimerLLC/csla#1845]
**Description:**
I am using Atlassian BitBucket cloud build pipeline (some flavour of Linux) and have a unit tests in a separate test project which I am trying to run the tests for.  i.e. dotnet test
The test project is referencing the business layer project which has a bunch of CSLA based classes.  This is a DotNet Core 3.1 Web Api.

The build pipeline fails at the dotnet test with initially a bunch of warnings that files cannot be found and as part of that it tries a number of times and then fails.  Running dotnet test on a Windows PC works correctly.

**Version and Platform**
CSLA version: 5.3.1
OS: Linux (Atlassian BitBucket cloud)
Platform: ASP.NET Core 3.1

**Code that Fails**
Here is an excerpt from my build pipeline file.

```
image: mcr.microsoft.com/dotnet/core/sdk:3.1

pipelines:
  branches:
    develop:
        - step:
            name: Build and Test
            caches:
              - dotnetcore
            script:
              - export ENV_NAME=develop
              - export PROJECT_NAME=Myapi
              - export ZIP_FILE=Myapi-dev.zip
              - export TEST_PROJECT=Myapi.Tests
              - dotnet restore -s https://api.nuget.org/v3/index.json
              - dotnet build $PROJECT_NAME
              - dotnet restore $TEST_PROJECT
              - dotnet test $TEST_PROJECT
```

**Stack Trace or Exception Detail**
```
/usr/share/dotnet/sdk/3.1.402/Microsoft.Common.CurrentVersion.targets(4364,5): warning MSB3026: Could not copy "/root/.nuget/packages/microsoft.testplatform.objectmodel/16.7.1/lib/netstandard2.0/pt-BR/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll" to "bin/Debug/netcoreapp3.1/pt-BR/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll". Beginning retry 1 in 1000ms. Could not find a part of the path '/opt/atlassian/pipelines/agent/build/Myapi.Tests/bin/Debug/netcoreapp3.1/pt-BR/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll'.  [/opt/atlassian/pipelines/agent/build/Myapi.Tests/Myapi.Tests.csproj]
/usr/share/dotnet/sdk/3.1.402/Microsoft.Common.CurrentVersion.targets(4364,5): warning MSB3026: Could not copy "/root/.nuget/packages/microsoft.testplatform.objectmodel/16.7.1/lib/netstandard2.0/pt-BR/Microsoft.TestPlatform.CoreUtilities.resources.dll" to "bin/Debug/netcoreapp3.1/pt-BR/Microsoft.TestPlatform.CoreUtilities.resources.dll". Beginning retry 1 in 1000ms. Could not find a part of the path '/opt/atlassian/pipelines/agent/build/Myapi.Tests/bin/Debug/netcoreapp3.1/pt-BR/Microsoft.TestPlatform.CoreUtilities.resources.dll'.  [/opt/atlassian/pipelines/agent/build/Myapi.Tests/Myapi.Tests.csproj]
/usr/share/dotnet/sdk/3.1.402/Microsoft.Common.CurrentVersion.targets(4364,5): warning MSB3026: Could not copy "/root/.nuget/packages/microsoft.testplatform.testhost/16.7.1/lib/netcoreapp2.1/pt-BR/Microsoft.TestPlatform.CrossPlatEngine.resources.dll" to "bin/Debug/netcoreapp3.1/pt-BR/Microsoft.TestPlatform.CrossPlatEngine.resources.dll". Beginning retry 1 in 1000ms. Could not find a part of the path '/opt/atlassian/pipelines/agent/build/Myapi.Tests/bin/Debug/netcoreapp3.1/pt-BR/Microsoft.TestPlatform.CrossPlatEngine.resources.dll'.  [/opt/atlassian/pipelines/agent/build/Myapi.Tests/Myapi.Tests.csproj]
/usr/share/dotnet/sdk/3.1.402/Microsoft.Common.CurrentVersion.targets(4364,5): warning MSB3026: Could not copy "/root/.nuget/packages/microsoft.testplatform.testhost/16.7.1/lib/netcoreapp2.1/pt-BR/Microsoft.TestPlatform.CommunicationUtilities.resources.dll" to "bin/Debug/netcoreapp3.1/pt-BR/Microsoft.TestPlatform.CommunicationUtilities.resources.dll". Beginning retry 1 in 1000ms. Could not find a part of the path '/opt/atlassian/pipelines/agent/build/Myapi.Tests/bin/Debug/netcoreapp3.1/pt-BR/Microsoft.TestPlatform.CommunicationUtilities.resources.dll'.  [/opt/atlassian/pipelines/agent/build/Myapi.Tests/Myapi.Tests.csproj]
/usr/share/dotnet/sdk/3.1.402/Microsoft.Common.CurrentVersion.targets(4364,5): warning MSB3026: Could not copy "/root/.nuget/packages/microsoft.testplatform.testhost/16.7.1/lib/netcoreapp2.1/pt-BR/Microsoft.TestPlatform.CommunicationUtilities.resources.dll" to "bin/Debug/netcoreapp3.1/pt-BR/Microsoft.TestPlatform.CommunicationUtilities.resources.dll". Beginning retry 2 in 1000ms. Could not find a part of the path '/opt/atlassian/pipelines/agent/build/Myapi.Tests/bin/Debug/netcoreapp3.1/pt-BR/Microsoft.TestPlatform.CommunicationUtilities.resources.dll'.  [/opt/atlassian/pipelines/agent/build/Myapi.Tests/Myapi.Tests.csproj]
```

**Additional context**
It appears that the resource file / folder name is output as lower-case in the build process but dotnet test is expecting it to be pt-BR.

**Workaround**
To workaround this issue I modified the pipeline to do a simple copy and rename.  Note this did not seem to be an issue on any of the other resource file/folder names.

```
...
- dotnet build $PROJECT_NAME
            # Workaround for resource file case sensitivity issue
            - ls -lR .
            - cp -R ./Myapi/bin ./Myapi.Tests/bin
            - cp -R ./Myapi/bin/Debug/netcoreapp3.1/pt-br ./Myapi.Tests/bin/Debug/netcoreapp3.1/pt-BR
            - dotnet test $TEST_PROJECT
...
```
